<?php
/**
 * EmbeddingSearch — meaning-based (not keyword-based) archive search.
 *
 * Lexical search (FULLTEXT/LIKE/stemming, see SemanticSearch.php despite its name)
 * requires the query and the content to share actual words. This is the layer for
 * when they don't: "which place is Tiv located?" has zero vocabulary overlap with
 * "The Origins of the Tiv People", but both are clearly about the same thing.
 *
 * Vectors are generated by a dedicated local embedding model via Ollama (never an
 * external API — same self-contained principle as the rest of this app's AI features)
 * and stored as packed binary floats directly on archive_search_index. At query time
 * the query text is embedded once, then compared against every stored vector by plain
 * cosine similarity — the archive is small enough (low thousands of rows) that a
 * linear scan in PHP is fast; no vector database needed.
 *
 * Deliberately a LAST-RESORT fallback, not a replacement for lexical search: it's
 * slower (one Ollama round-trip per query) and fuzzier (a similarity score, not an
 * exact/prefix match), so ArchiveIntelligence only reaches for it when the precise
 * paths have already come up empty.
 */
class EmbeddingSearch
{
    private PDO $db;

    public function __construct(PDO $db)
    {
        $this->db = $db;
    }

    /**
     * Embed the query and return the top archive_search_index rows by cosine
     * similarity, filtered to EMBEDDING_MIN_SIMILARITY and above. Returns [] on any
     * failure (Ollama unavailable, no embedded rows yet, etc.) — never throws, so a
     * caller can treat this exactly like any other "found nothing" search result.
     */
    public function search(string $query, int $limit = 5): array
    {
        if (trim($query) === '') return [];

        $queryVector = OllamaClient::embed($query);
        if ($queryVector === null) return [];

        $scored = [];
        // Chunked read (not one giant fetchAll) so this stays cheap even as the
        // archive grows well past today's ~6k rows.
        //
        // Minimum combined-length filter: very short entries (a bare dictionary word
        // like "Or Tiv" = "A Tiv man", 15 characters total) embed ambiguously and can
        // score a HIGHER cosine similarity than a genuinely relevant, information-dense
        // article — a real, measured failure mode, not a hypothetical one (confirmed:
        // that exact word outranked "The Origins of the Tiv People" for a location
        // question). Short entries are already served well by exact/lexical search
        // anyway, so excluding them from this meaning-based fallback only removes noise.
        $stmt = $this->db->query(
            "SELECT id, source_table, source_id, content_type, primary_text, secondary_text,
                    excerpt, url, embedding
             FROM archive_search_index
             WHERE embedding IS NOT NULL
               AND (CHAR_LENGTH(primary_text) + CHAR_LENGTH(COALESCE(secondary_text,''))
                    + CHAR_LENGTH(COALESCE(excerpt,''))) >= 40"
        );
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            $vector = self::unpack($row['embedding']);
            if ($vector === null) continue;
            $similarity = self::cosineSimilarity($queryVector, $vector);
            if ($similarity < EMBEDDING_MIN_SIMILARITY) continue;
            unset($row['embedding']); // never carry raw vector bytes past this point
            $row['_similarity'] = $similarity;
            $scored[] = $row;
        }

        usort($scored, fn($a, $b) => $b['_similarity'] <=> $a['_similarity']);
        return array_slice($scored, 0, $limit);
    }

    /**
     * Embed and store every archive_search_index row that doesn't have a vector yet
     * (embedding IS NULL) — new content indexed since the last backfill, or content
     * indexed before this feature existed. Safe to run repeatedly (idempotent: rows
     * that already have an embedding are skipped). Returns [succeeded, failed] counts.
     *
     * @return array{0:int,1:int}
     */
    public function backfillMissing(int $batchLimit = 500): array
    {
        $stmt = $this->db->prepare(
            "SELECT id, primary_text, secondary_text, excerpt
             FROM archive_search_index
             WHERE embedding IS NULL
             LIMIT {$batchLimit}"
        );
        $stmt->execute();
        $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

        $update = $this->db->prepare("UPDATE archive_search_index SET embedding = ? WHERE id = ?");

        $ok = 0;
        $failed = 0;
        foreach ($rows as $row) {
            $text = trim(($row['primary_text'] ?? '') . '. ' . ($row['secondary_text'] ?? ''));
            if ($text === '') {
                $text = $row['excerpt'] ?? '';
            }
            if (trim($text) === '') {
                $failed++;
                continue;
            }

            $vector = OllamaClient::embed(mb_substr($text, 0, 2000));
            if ($vector === null) {
                $failed++;
                continue;
            }

            $update->execute([self::pack($vector), $row['id']]);
            $ok++;
        }

        return [$ok, $failed];
    }

    /**
     * Embed a single archive_search_index row immediately by its own id — used by
     * ContentIndexer right after it writes/updates a row, so new content becomes
     * semantically searchable without waiting for the next backfill pass. Best-effort:
     * swallows failures (a transient Ollama hiccup shouldn't block content indexing),
     * leaving the row for the next backfillMissing() pass to pick up.
     */
    public function embedRow(int $searchIndexId, string $text): bool
    {
        if (trim($text) === '') return false;
        $vector = OllamaClient::embed(mb_substr($text, 0, 2000));
        if ($vector === null) return false;

        $stmt = $this->db->prepare("UPDATE archive_search_index SET embedding = ? WHERE id = ?");
        $stmt->execute([self::pack($vector), $searchIndexId]);
        return true;
    }

    /**
     * Score cosine similarity between $query and each candidate's already-stored
     * embedding, keyed by archive_search_index.id. Reuses this class's existing
     * vector storage/math for pre-generation evidence-relevance filtering — "does
     * this candidate actually answer the question, not just relate to it" — as
     * distinct from search()'s own retrieval role.
     *
     * @param array<string,int> $indexIdsByKey caller key => archive_search_index.id
     * @return array<string,?float> same keys => similarity, or null when unscoreable
     *         (no stored embedding yet, or $query itself couldn't be embedded) —
     *         callers MUST treat null as "unscored", never as "irrelevant".
     */
    public function scoreCandidates(string $query, array $indexIdsByKey): array
    {
        $result = array_fill_keys(array_keys($indexIdsByKey), null);
        if (trim($query) === '' || empty($indexIdsByKey)) return $result;

        $queryVector = OllamaClient::embed($query);
        if ($queryVector === null) return $result;

        $ids = array_values(array_unique(array_map('intval', $indexIdsByKey)));
        $placeholders = implode(',', array_fill(0, count($ids), '?'));
        $stmt = $this->db->prepare(
            "SELECT id, embedding FROM archive_search_index WHERE id IN ({$placeholders})"
        );
        $stmt->execute($ids);

        $vectorsById = [];
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            $vector = self::unpack($row['embedding']);
            if ($vector !== null) {
                $vectorsById[(int) $row['id']] = $vector;
            }
        }

        foreach ($indexIdsByKey as $key => $indexId) {
            $vector = $vectorsById[(int) $indexId] ?? null;
            if ($vector !== null) {
                $result[$key] = self::cosineSimilarity($queryVector, $vector);
            }
        }

        return $result;
    }

    // ─────────────────────────────────────────────────────────────
    // Vector math / (de)serialization
    // ─────────────────────────────────────────────────────────────

    /** Pack a float vector into a compact binary blob (4 bytes/dimension). */
    public static function pack(array $vector): string
    {
        return pack('g*', ...$vector);
    }

    /** Unpack a binary blob back into a float vector, or null if malformed. */
    private static function unpack(?string $blob): ?array
    {
        if ($blob === null || $blob === '') return null;
        $floats = @unpack('g*', $blob);
        return $floats !== false ? array_values($floats) : null;
    }

    private static function cosineSimilarity(array $a, array $b): float
    {
        $n = min(count($a), count($b));
        if ($n === 0) return 0.0;

        $dot = 0.0;
        $magA = 0.0;
        $magB = 0.0;
        for ($i = 0; $i < $n; $i++) {
            $dot  += $a[$i] * $b[$i];
            $magA += $a[$i] * $a[$i];
            $magB += $b[$i] * $b[$i];
        }
        if ($magA <= 0.0 || $magB <= 0.0) return 0.0;

        return $dot / (sqrt($magA) * sqrt($magB));
    }
}
