<?php
require_once BASE_PATH . '/services/OutreachMailer.php';
require_once BASE_PATH . '/services/OllamaClient.php';
require_once BASE_PATH . '/models/DailyWord.php';
require_once BASE_PATH . '/models/TivProverb.php';
require_once BASE_PATH . '/models/TivFestival.php';
require_once BASE_PATH . '/models/TivName.php';
require_once BASE_PATH . '/models/HistoricalFigure.php';
require_once BASE_PATH . '/models/TimelineEvent.php';

/**
 * Builds a newsletter issue (subject + HTML + plain text) from real archive
 * data — never AI-hallucinated content. An optional short intro paragraph
 * is generated by the local Ollama model, but the actual item list is
 * always a direct, accurate reflection of what's really in the database.
 */
class NewsletterGeneratorService
{
    public static function generate(string $issueType): array
    {
        return match ($issueType) {
            'new_words'      => self::buildNewWords(),
            'featured_items' => self::buildFeaturedItems(),
            'top_five'       => self::buildTopFive(),
            'weekly_summary', 'custom' => self::buildWeeklySummary(),
            default => throw new RuntimeException("Unknown newsletter type: {$issueType}"),
        };
    }

    private static function buildWeeklySummary(): array
    {
        $words = (new DailyWord())->recent(3);
        $featured = self::collectFeatured(4);
        $topViewed = self::collectMostViewed(3);

        $intro = self::generateIntro(
            'a weekly roundup email for a Tiv cultural heritage newsletter, introducing new words, featured content, and popular articles from the archive'
        );

        $sections = [
            ['title' => 'New Words This Week', 'items' => self::formatItems($words, 'tiv_word', 'english_meaning', 'word')],
            ['title' => 'Featured Content', 'items' => $featured],
            ['title' => 'Popular This Week', 'items' => $topViewed],
        ];

        return self::render('This Week at the Tiv Heritage Archive', $intro, $sections);
    }

    private static function buildNewWords(): array
    {
        $words = (new DailyWord())->recent(10);
        $intro = self::generateIntro('an email introducing 10 newly featured Tiv words to language learners');
        return self::render('New Tiv Words to Learn', $intro, [
            ['title' => 'New Words', 'items' => self::formatItems($words, 'tiv_word', 'english_meaning', 'word')],
        ]);
    }

    private static function buildFeaturedItems(): array
    {
        $featured = self::collectFeatured(10);
        $intro = self::generateIntro('an email highlighting hand-picked featured content from a Tiv cultural heritage archive');
        return self::render('Featured on the Tiv Heritage Archive', $intro, [
            ['title' => 'Featured Content', 'items' => $featured],
        ]);
    }

    private static function buildTopFive(): array
    {
        $top = self::collectMostViewed(5);
        $intro = self::generateIntro('an email counting down the 5 most popular articles this month on a Tiv cultural heritage archive');
        return self::render('Top 5 Most Popular This Month', $intro, [
            ['title' => 'Top 5 Articles', 'items' => $top],
        ]);
    }

    /** @return array<int, array{title:string, url:string, meta:string}> */
    private static function collectFeatured(int $limit): array
    {
        $items = [];
        $sources = [
            ['model' => new TivProverb(), 'title' => 'tiv_text', 'path' => 'proverb', 'label' => 'Proverb'],
            ['model' => new TivFestival(), 'title' => 'tiv_name', 'path' => 'festival', 'label' => 'Festival'],
            ['model' => new TivName(), 'title' => 'tiv_name', 'path' => 'name', 'label' => 'Name'],
        ];

        foreach ($sources as $src) {
            foreach ($src['model']->featured(2) as $row) {
                $items[] = [
                    'title' => $row[$src['title']] ?? '(untitled)',
                    'url' => rtrim(SITE_URL, '/') . '/' . $src['path'] . '/' . $row['id'],
                    'meta' => $src['label'],
                ];
                if (count($items) >= $limit) return $items;
            }
        }

        return $items;
    }

    /** @return array<int, array{title:string, url:string, meta:string}> */
    private static function collectMostViewed(int $limit): array
    {
        $items = [];
        $figures = (new HistoricalFigure())->mostViewed((int) ceil($limit / 2));
        foreach ($figures as $row) {
            $items[] = [
                'title' => $row['english_name'] ?? $row['tiv_name'] ?? '(untitled)',
                'url' => rtrim(SITE_URL, '/') . '/historical-figure/' . $row['id'],
                'meta' => number_format($row['view_count']) . ' views',
            ];
        }

        $events = (new TimelineEvent())->mostViewed($limit - count($items));
        foreach ($events as $row) {
            $items[] = [
                'title' => $row['title'] ?? '(untitled)',
                'url' => rtrim(SITE_URL, '/') . '/timeline-event/' . $row['id'],
                'meta' => number_format($row['view_count']) . ' views',
            ];
        }

        return array_slice($items, 0, $limit);
    }

    private static function formatItems(array $rows, string $titleField, string $metaField, string $path): array
    {
        return array_map(fn($r) => [
            'title' => $r[$titleField] ?? '(untitled)',
            'url' => rtrim(SITE_URL, '/') . '/' . $path . '/' . $r['id'],
            'meta' => $r[$metaField] ?? '',
        ], $rows);
    }

    private static function generateIntro(string $context): string
    {
        $fallback = 'Here is what\'s new at the Tiv Heritage Archive this week — thank you for helping us preserve Tiv language, history, and culture.';

        if (!OLLAMA_ENABLED) {
            return $fallback;
        }

        $text = OllamaClient::generate(
            'You write short, warm email introductions for the Tiv Heritage Archive. Respond with 2-3 sentences of plain text only — no greeting, no sign-off, no markdown.',
            "Write a short intro paragraph for {$context}."
        );

        return $text ? trim($text) : $fallback;
    }

    /**
     * @param array<int, array{title:string, items:array}> $sections
     */
    private static function render(string $subject, string $intro, array $sections): array
    {
        $siteName = defined('SITE_NAME') ? SITE_NAME : 'Tiv Heritage Archive';
        $siteUrl = defined('SITE_URL') ? SITE_URL : '';

        $htmlSections = '';
        $textSections = '';

        foreach ($sections as $section) {
            if (empty($section['items'])) continue;

            $htmlSections .= '<h3 style="color:#5C3A21;font-size:16px;margin:24px 0 10px;">' . htmlspecialchars($section['title']) . '</h3><ul style="padding-left:20px;margin:0;">';
            $textSections .= "\n" . strtoupper($section['title']) . "\n" . str_repeat('-', strlen($section['title'])) . "\n";

            foreach ($section['items'] as $item) {
                $htmlSections .= '<li style="margin-bottom:8px;"><a href="' . htmlspecialchars($item['url']) . '" style="color:#5C3A21;font-weight:600;">' . htmlspecialchars($item['title']) . '</a>'
                    . (!empty($item['meta']) ? ' <span style="color:#8a7a6a;font-size:13px;">— ' . htmlspecialchars($item['meta']) . '</span>' : '')
                    . '</li>';
                $textSections .= '- ' . $item['title'] . (!empty($item['meta']) ? ' (' . $item['meta'] . ')' : '') . ': ' . $item['url'] . "\n";
            }
            $htmlSections .= '</ul>';
        }

        $htmlBody = '<p style="margin:0 0 20px;">' . nl2br(htmlspecialchars($intro)) . '</p>' . $htmlSections
            . '<p style="margin-top:28px;"><a href="' . htmlspecialchars($siteUrl) . '" style="color:#C8A951;">Visit the Tiv Heritage Archive &rarr;</a></p>';

        $textBody = $intro . "\n" . $textSections . "\nVisit: " . $siteUrl . "\n";

        return [
            'subject' => $subject,
            'html_body' => OutreachMailer::buildBody($htmlBody, []),
            'text_body' => $textBody,
        ];
    }
}
