<?php
/**
 * SeoHelper - shared utilities for meta descriptions, og:image, JSON-LD,
 * breadcrumbs, and canonical URL slugs across the public-facing content types.
 */
class SeoHelper
{
    public static function truncate(string $text, int $len = 155): string
    {
        $text = trim(preg_replace('/\s+/', ' ', strip_tags($text)));
        if (mb_strlen($text) <= $len) {
            return $text;
        }
        $truncated = mb_substr($text, 0, $len);
        $lastSpace = mb_strrpos($truncated, ' ');
        if ($lastSpace !== false) {
            $truncated = mb_substr($truncated, 0, $lastSpace);
        }
        return rtrim($truncated, " .,;:-") . '…';
    }

    /**
     * Returns the first non-empty candidate, truncated for a meta description.
     * @param array<int, string|null> $candidates
     */
    public static function describe(array $candidates, string $fallback, int $len = 155): string
    {
        foreach ($candidates as $candidate) {
            if (!empty(trim((string) $candidate))) {
                return self::truncate((string) $candidate, $len);
            }
        }
        return self::truncate($fallback, $len);
    }

    public static function ogImage(?string $filename, string $subdir = 'images'): string
    {
        if (!empty($filename)) {
            return UPLOADS_URL . '/' . trim($subdir, '/') . '/' . $filename;
        }
        return SITE_URL . '/favicon.png';
    }

    /**
     * @param array<int, array<string, mixed>> $graphs One or more schema.org associative arrays.
     */
    public static function jsonLd(array $graphs): string
    {
        $graphs = array_values(array_filter($graphs));
        if (empty($graphs)) {
            return '';
        }
        $data = count($graphs) === 1
            ? $graphs[0]
            : ['@context' => 'https://schema.org', '@graph' => array_map(
                static function (array $g): array {
                    unset($g['@context']);
                    return $g;
                },
                $graphs
            )];

        $json = json_encode(
            $data,
            JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP
        );

        return '<script type="application/ld+json">' . $json . '</script>';
    }

    /**
     * Converts the existing ['label' => ..., 'url' => ...] breadcrumb shape
     * into a schema.org BreadcrumbList graph.
     * @param array<int, array{label: string, url: ?string}> $crumbs
     */
    public static function breadcrumbListSchema(array $crumbs): array
    {
        $items = [];
        foreach ($crumbs as $i => $crumb) {
            $entry = [
                '@type'    => 'ListItem',
                'position' => $i + 1,
                'name'     => $crumb['label'],
            ];
            if (!empty($crumb['url'])) {
                $entry['item'] = $crumb['url'];
            }
            $items[] = $entry;
        }
        return [
            '@context'        => 'https://schema.org',
            '@type'           => 'BreadcrumbList',
            'itemListElement' => $items,
        ];
    }

    public static function slugify(string $text): string
    {
        $slug = strtolower(trim($text));
        $slug = preg_replace('/[^a-z0-9]+/', '-', $slug);
        return trim($slug, '-');
    }

    public static function canonicalSlugPath(string $prefix, int $id, string $name): string
    {
        // Bounded so long free-text names (e.g. a full proverb) don't produce
        // unwieldy URLs; the id remains authoritative for lookup either way.
        $slug = self::slugify(self::truncate($name, 60));
        return $slug !== '' ? "{$prefix}/{$id}-{$slug}" : "{$prefix}/{$id}";
    }

    /**
     * Deterministic filename for a responsive image variant generated by the
     * image optimization pipeline (bin/optimize-images.php / ImageVariantGenerator).
     */
    public static function variantUrl(string $original, int $width, string $ext, string $subdir = 'images'): string
    {
        $base = preg_replace('/\.[^.]+$/', '', $original);
        return UPLOADS_URL . '/' . trim($subdir, '/') . "/{$base}-{$width}w.{$ext}";
    }

    /**
     * Renders a <picture> with WebP + responsive srcset for a hero/detail
     * image, falling back to a plain <img> when no variants exist (e.g. the
     * source was narrower than the smallest variant width and none were
     * generated - see ImageVariantGenerator). $imgStyle/$imgAttrs are passed
     * through verbatim onto the <img> tag for layout parity with the
     * surrounding markup.
     */
    public static function heroPicture(string $filename, string $alt, string $imgStyle = '', string $imgAttrs = ''): string
    {
        $original = self::ogImage($filename);
        $img = '<img src="' . htmlspecialchars($original) . '" alt="' . htmlspecialchars($alt) . '"'
             . ($imgStyle !== '' ? ' style="' . htmlspecialchars($imgStyle) . '"' : '')
             . ($imgAttrs !== '' ? ' ' . $imgAttrs : '')
             . '>';

        $base = preg_replace('/\.[^.]+$/', '', $filename);
        $webp400Path = UPLOADS_PATH . "/images/{$base}-400w.webp";
        $webp800Path = UPLOADS_PATH . "/images/{$base}-800w.webp";
        if (!is_file($webp400Path) && !is_file($webp800Path)) {
            return $img;
        }

        $srcset = [];
        foreach ([400, 800] as $w) {
            if (is_file(UPLOADS_PATH . "/images/{$base}-{$w}w.webp")) {
                $srcset[] = self::variantUrl($filename, $w, 'webp') . " {$w}w";
            }
        }

        return '<picture><source type="image/webp" srcset="' . htmlspecialchars(implode(', ', $srcset)) . '">' . $img . '</picture>';
    }
}
